kind: Service
apiVersion: v1
metadata:
  name: gsp-acr-service
spec:
  type: NodePort
  selector:
    app: gsp-acr
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30700
    targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gsp-acr
  labels:
    app: gsp-acr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gsp-acr
  template:
    metadata:
      labels:
        app: gsp-acr
        version: "1.0.2"
    spec:
      containers:
      - name: gsp-acr
        image: docker.gsp.sicc.co.kr/acr:1.0.2
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: dev
        - name: spring.cloud.config.uri
          value: http://100.96.252.193:8888
        ports:
        - name: http
          containerPort: 8080